### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by xietao1233** [IonicaBizau/image-parser#16]
In file included from ../src/lib/png/png.c:14:0:
../src/lib/png/pngpriv.h:805:4: error: #error ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"
 #  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
    ^~~~~
lwip_decoder.target.mk:172: recipe for target 'Release/obj.target/lwip_decoder/src/lib/png/png.o' failed
make: *** [Release/obj.target/lwip_decoder/src/lib/png/png.o] Error 1
make: Leaving directory '/home/xxx/src/node/test/node_modules/lwip2/node_modules/lwip/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/xxx/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/home/xxx/.nvm/versions/node/v10.15.3/bin/node" "/home/xxx/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/xxx/src/node/test/node_modules/lwip2/node_modules/lwip
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxx/.npm/_logs/2019-06-22T06_19_14_699Z-debug.log
It seems like lwip failed to be intalled. Please check the errors.
npm WARN ts-node@8.3.0 requires a peer of typescript@>=2.0 but none is installed. You must install peer dependencies yourself.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwip2@1.0.14 install: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip2@1.0.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxx/.npm/_logs/2019-06-22T06_19_14_850Z-debug.log

**Comment by kanjiman** [comment]
I am also having build errors in relation to the lwip library failing for being so old. Please update image-parser to use lwip2 or a non-deprecated replacement to solve these errors, I spent hours trying to get it to work to no avail.
